FROM i2incommon/grouper:5.9.0

# TODO: Add SSH configuration for Azure App Service
# https://learn.microsoft.com/en-us/azure/app-service/configure-custom-container?tabs=debian&pivots=container-linux#enable-ssh